// TODO TIPO DE COMENTÁRIO DEVE HAVER AS DUAS BARRAS "//" NO ÍNICIO;
 // NESTE JAVASCRIPT, O COMENTÁRIO FICA NA COR VERDE;
   // POSSO FAZER A QUALQUER INSTANTE E MOMENTO DURANTE A CODAÇÃO;

   // O COMENTARIO FUNCIONA COMO UMA "ANOTAÇÃO";
console.log("Olá, mundo");
   // POSSO FAZER UMA ANOTAÇÃO OU OBSERVAÇÃO DE UM COMANDO/CODIGO ATRAVÉS DO COMENTÁRIO;
   // LEMBRANDO QUE O COMENTÁRIO NÃO APARECERÁ NO TERMINAL OU NA EXECUÇÃO DO CÓDIGO.

   // EXISTE TAMBÉM O COMENTÁRIO POR BLOCO... EXEMPLOS ABAIXO:
   /* 
   POSSO FAZER DIVERSOS COMENTARIOS
   E UM ABAIXO DO OUTRO EM LINHAS DIFERENTES.
   HAHAHAHAHA
   */