/*
NO ARQUIVO HTML:
* APRENDI QUE POSSO ACRESCENTAR O PADRÃO HTML PARA CRIAR UM SITE
APENAS DIGITANDO O "!" E APERTANDO O ENTER OU DIGITAR "HTML:5" E APERTAR ENTER.
* CASO O ARQUIVO NO GERAL ESTEJA BAGUNÇADO, COM O BOTÃO DIREITO DO MOUSE É POSSIVEL ORGANZAR
O DOCUMENTO E DEIXAR MAIS BONITO.
* NESTA AULA TAMBÉM É EXPLICADO COMO DEIXAR OS CODIGOS E OS SCRIPTS MAIS PROFISSIONAIS DENTRO
DO HTML E UTILIZANDO O JAVASCRIPT.
*/
